name: CoreEngine
version: ${project.version}
main: dev.thelecrafter.dimensionz.rpg.engine.Engine
api-version: 1.16
authors: [ TheLeCrafter ]
description: Replace the vanilla combat/health/... system with this custom one
permissions:
  coreengine.grief.armorstand:
    default: false
  coreengine.grief.world.place:
    default: false
  coreengine.grief.world.break:
    default: false
commands:
  openstatsmenu:
    description: Opens the stats menu
  item:
    permission: coreengine.commands.item
